const FREQUENCIES = [261.63, 293.66, 329.63, 392.0];
const THEMES = [[0,0,2,2,3,3,2,1,1,1,1,0,0,0,0,3,3,2,1,1,0],[2,2,3,2,1,0,1,2,2,2,2,1,1,1,1,2,1,0],[0,2,3,2,0,2,3,2,1,1,2,1,0,0,2,0]];
const background = typeof Image === "undefined" ? null : new Image();
if (background) background.src = new URL("../assets/piano-duet-bg.png", import.meta.url).href;
let audioContext;
export function preparePianoAudio() { try { audioContext ||= new AudioContext(); audioContext.resume?.(); } catch {} }
function tone(lane, strength = 1) { try { preparePianoAudio(); const now = audioContext.currentTime; [1,2].forEach((harmonic, index) => { const oscillator = audioContext.createOscillator(), gain = audioContext.createGain(); oscillator.type = index ? "sine" : "triangle"; oscillator.frequency.value = FREQUENCIES[lane] * harmonic; gain.gain.setValueAtTime(.0001, now); gain.gain.exponentialRampToValueAtTime(.14 * strength / harmonic, now + .01); gain.gain.exponentialRampToValueAtTime(.0001, now + .4); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(now); oscillator.stop(now + .44); }); } catch {} }
function notesFor(players) { const theme = THEMES[Math.floor(Math.random() * THEMES.length)], notes = []; for (let i = 0; i < 88; i += 1) notes.push({ frame: 210 + i * 34, lane: theme[i % theme.length], player: players === 2 ? i % 2 : 0, hit: false }); return notes; }
export function createPianoState(players = 1) { return { type: "piano", players: [{ score: 0, combo: 0, best: 0, judge: "準備" }, { score: 0, combo: 0, best: 0, judge: "準備" }], playerCount: players, notes: notesFor(players), frame: 0, countdown: 180, winner: null, finished: false, held: [[false,false,false,false], [false,false,false,false]] }; }
function inputs(input = {}) { return [Boolean(input.left), Boolean(input.up), Boolean(input.down), Boolean(input.right)]; }
function scoreNote(game, player, lane) { const note = game.notes.filter((item) => !item.hit && item.player === player && item.lane === lane).sort((a, b) => Math.abs(a.frame - game.frame) - Math.abs(b.frame - game.frame))[0], delta = note ? Math.abs(note.frame - game.frame) : Infinity, data = game.players[player]; if (delta > 18) { data.combo = 0; data.judge = "MISS"; return; } note.hit = true; const perfect = delta < 6, good = delta < 12; data.score += perfect ? 1000 + data.combo * 12 : good ? 650 + data.combo * 8 : 350; data.combo += 1; data.best = Math.max(data.best, data.combo); data.judge = perfect ? "Perfect" : good ? "Good" : "Nice"; tone(lane, perfect ? 1 : .72); }
export function updatePiano(game, first = {}, second = {}, useAi = false) { if (game.finished) return game; game.frame += 1; if (game.countdown > 0) { game.countdown -= 1; return game; } const all = [inputs(first), inputs(second)]; if (useAi) { const next = game.notes.find((note) => !note.hit && note.player === 1); if (next && Math.abs(next.frame - game.frame) < 2) all[1][next.lane] = true; } all.forEach((lanes, player) => lanes.forEach((pressed, lane) => { if (pressed && !game.held[player][lane]) scoreNote(game, player, lane); game.held[player][lane] = pressed; })); game.notes.forEach((note) => { if (!note.hit && game.frame - note.frame > 25) { note.hit = true; game.players[note.player].combo = 0; game.players[note.player].judge = "MISS"; } }); if (game.frame > game.notes.at(-1).frame + 170) { game.finished = true; game.winner = game.playerCount === 1 ? 0 : game.players[0].score === game.players[1].score ? -1 : game.players[0].score > game.players[1].score ? 0 : 1; } return game; }
function rounded(ctx, x, y, w, h, r, fill) { ctx.fillStyle = fill; ctx.beginPath(); ctx.roundRect(x, y, w, h, r); ctx.fill(); }
export function drawPiano(canvas, game) { const ctx = canvas.getContext("2d"), w = 800, h = 500; ctx.clearRect(0,0,w,h); ctx.fillStyle="#f9f6ee"; ctx.fillRect(0,0,w,h); if (background?.complete && background.naturalWidth) { ctx.globalAlpha=.17; ctx.drawImage(background,0,0,w,h); ctx.globalAlpha=1; } ctx.fillStyle="rgba(255,255,255,.87)";ctx.fillRect(54,28,692,352);ctx.strokeStyle="#ddc89f";ctx.lineWidth=2;ctx.strokeRect(54,28,692,352);ctx.font="700 22px sans-serif";ctx.fillStyle="#513c29";ctx.textAlign="center";ctx.fillText("雙人鋼琴對奏",400,57); [[0,76,"#ec6f59"],[1,420,"#2f9d9b"]].forEach(([player,x,color])=>{rounded(ctx,x,75,304,238,15,"rgba(255,255,255,.75)");ctx.fillStyle=color;ctx.fillRect(x,75,304,4);ctx.font="700 14px sans-serif";ctx.fillStyle=color;ctx.textAlign="left";ctx.fillText(`玩家 ${player+1}  ${game.players[player].score.toLocaleString()}`,x+12,99);ctx.textAlign="right";ctx.fillStyle="#775f49";ctx.fillText(`連擊 ×${game.players[player].combo}`,x+292,99);for(let lane=0;lane<4;lane+=1){const laneX=x+12+lane*72;ctx.fillStyle=player?"rgba(47,157,155,.08)":"rgba(236,111,89,.08)";ctx.fillRect(laneX,110,60,166);ctx.strokeStyle=player?"rgba(47,157,155,.21)":"rgba(236,111,89,.21)";ctx.strokeRect(laneX,110,60,166);}game.notes.filter((note)=>!note.hit&&note.player===player&&note.frame-game.frame<150&&note.frame-game.frame>-30).forEach((note)=>rounded(ctx,x+18+note.lane*72,250-(note.frame-game.frame)*.92,48,16,8,color));ctx.fillStyle="#c9a95e";ctx.fillRect(x+12,264,280,5);ctx.font="700 15px sans-serif";ctx.textAlign="center";ctx.fillStyle=color;ctx.fillText(game.players[player].judge,x+152,301);});rounded(ctx,52,370,696,120,12,"#bd9160");for(let index=0;index<14;index+=1){const x=58+index*50;rounded(ctx,x,386,48,94,3,"#fffdf8");ctx.strokeStyle="#a9794a";ctx.strokeRect(x,386,48,94);}[1,2,4,5,6,8,9,11,12].forEach((index)=>rounded(ctx,58+index*50-15,386,28,57,4,"#2d2925"));ctx.font="700 12px sans-serif";ctx.fillStyle="#745635";ctx.textAlign="center";ctx.fillText("P1  ←  ↑  ↓  →",230,482);ctx.fillText("P2  A  W  S  D",570,482);if(game.countdown>0||game.finished){ctx.fillStyle="rgba(55,41,27,.62)";ctx.fillRect(265,144,270,116);ctx.fillStyle="#fff9ed";ctx.font="700 62px sans-serif";ctx.textAlign="center";ctx.fillText(game.finished?(game.winner===-1?"平手":`P${game.winner+1} 獲勝`):Math.max(1,Math.ceil(game.countdown/60)),400,207);ctx.font="700 15px sans-serif";ctx.fillText(game.finished?"再按一次重新演奏":"準備演奏",400,238);}}
