export const RHYTHM_SONGS = [
  ["給愛麗絲","貝多芬"],["歡樂頌","貝多芬"],["土耳其進行曲","莫札特"],["小夜曲","莫札特"],["D 大調卡農","帕海貝爾"],["G 弦之歌","巴赫"],["小步舞曲","巴赫"],["春・四季","韋瓦第"],["冬・四季","韋瓦第"],["藍色多瑙河","小約翰・史特勞斯"],
  ["匈牙利舞曲第五號","布拉姆斯"],["胡桃鉗進行曲","柴可夫斯基"],["天鵝湖","柴可夫斯基"],["睡美人華爾滋","柴可夫斯基"],["卡門序曲","比才"],["哈巴奈拉","比才"],["威廉泰爾序曲","羅西尼"],["拉德斯基進行曲","老約翰・史特勞斯"],["晨歌・皮爾金組曲","葛利格"],["在山魔王宮中","葛利格"],
  ["月光奏鳴曲","貝多芬"],["悲愴奏鳴曲","貝多芬"],["命運交響曲","貝多芬"],["英雄交響曲","貝多芬"],["第 40 號交響曲","莫札特"],["魔笛夜后詠嘆調","莫札特"],["婚禮進行曲","孟德爾頌"],["仲夏夜之夢","孟德爾頌"],["春之歌","孟德爾頌"],["降 E 大調夜曲","蕭邦"],
  ["軍隊波蘭舞曲","蕭邦"],["雨滴前奏曲","蕭邦"],["愛之夢","李斯特"],["匈牙利狂想曲第二號","李斯特"],["天鵝・動物狂歡節","聖桑"],["水族館・動物狂歡節","聖桑"],["阿拉貝斯克第一號","德布西"],["月光・貝加馬斯克組曲","德布西"],["波麗露","拉威爾"],["展覽會之畫","穆索斯基"],
  ["斯拉夫舞曲第八號","德弗札克"],["新世界交響曲","德弗札克"],["芬蘭頌","西貝流士"],["卡農變奏曲","帕海貝爾"],["夏・四季","韋瓦第"],["秋・四季","韋瓦第"],["帕格尼尼隨想曲","拉赫曼尼諾夫"],["羅密歐與茱麗葉","柴可夫斯基"],["1812 序曲","柴可夫斯基"],["美麗的藍色多瑙河","小約翰・史特勞斯"]
].map(([title, composer], index) => ({ id: `classic-${index + 1}`, title, composer, bpm: 96 + (index * 7) % 74, difficulty: ["入門", "普通", "困難", "達人"][index % 4], license: "公版作品・本地合成演奏" }));

const clamp = (n, lo, hi) => Math.max(lo, Math.min(hi, n));
let audioContext;
const rhythmBackground = typeof Image === "undefined" ? null : new Image();
if (rhythmBackground) rhythmBackground.src = new URL("../assets/rhythm-room-bg.png", import.meta.url).href;
export function prepareRhythmAudio() { try { audioContext ||= new AudioContext(); audioContext.resume?.(); } catch {} }
function tone(kind, strength = 1, frequency = null, length = .11) { try { prepareRhythmAudio(); const now = audioContext.currentTime, osc = audioContext.createOscillator(), gain = audioContext.createGain(); osc.type = kind === "red" ? "sine" : "triangle"; osc.frequency.value = frequency || (kind === "red" ? 175 : 310); gain.gain.setValueAtTime(.0001, now); gain.gain.exponentialRampToValueAtTime(.13 * strength, now + .008); gain.gain.exponentialRampToValueAtTime(.0001, now + length); osc.connect(gain).connect(audioContext.destination); osc.start(now); osc.stop(now + length + .02); } catch {} }
function seeded(index) { let value = index * 92821 + 123; return () => { value = (value * 1664525 + 1013904223) >>> 0; return value / 4294967296; }; }
function pattern(index, bpm, players) { const random = seeded(index + 1), beat = Math.round(3600 / bpm), notes = []; for (let i = 8; i < 290; i += 1) { if (i % 2 || random() > .74) continue; notes.push({ frame: i * beat, kind: random() > .5 ? "red" : "blue", player: players === 2 ? notes.length % 2 : 0, hit: false }); } return notes; }
export function createRhythmState(songIndex = 0, players = 1) { const song = RHYTHM_SONGS[songIndex] || RHYTHM_SONGS[0]; return { type: "rhythm", songIndex, song, players: [{ score: 0, combo: 0, best: 0, judge: "準備" }, { score: 0, combo: 0, best: 0, judge: "準備" }], notes: pattern(songIndex, song.bpm, players), playerCount: players, frame: 0, countdown: 180, winner: null, finished: false, held: [{ red: false, blue: false }, { red: false, blue: false }] }; }
function read(input = {}) { return { red: Boolean(input.left || input.action), blue: Boolean(input.right) }; }
function hit(game, player, kind) { const next = game.notes.filter((note) => !note.hit && note.player === player && note.kind === kind).sort((a, b) => Math.abs(a.frame - game.frame) - Math.abs(b.frame - game.frame))[0]; const delta = next ? Math.abs(next.frame - game.frame) : Infinity; const data = game.players[player]; if (delta > 17) { data.combo = 0; data.judge = "MISS"; tone(kind, .35); return; } next.hit = true; const label = delta < 5 ? "良" : delta < 10 ? "可" : "連"; const points = label === "良" ? 1000 : label === "可" ? 650 : 350; data.score += points + Math.min(500, data.combo * 10); data.combo += 1; data.best = Math.max(data.best, data.combo); data.judge = label; tone(kind, 1); }
export function updateRhythm(game, first = {}, second = {}, useAi = false) { if (game.finished) return game; game.frame += 1; if (game.countdown > 0) { game.countdown -= 1; return game; } const beat = Math.round(3600 / game.song.bpm); if (game.frame % beat === 0) { const scale=[261.63,293.66,329.63,392,440,523.25,587.33,659.25]; tone("blue",.22,scale[(Math.floor(game.frame/beat)+game.songIndex*3)%scale.length],.18); } const inputs = [read(first), useAi ? { red: game.frame % 42 === 0, blue: game.frame % 59 === 0 } : read(second)]; inputs.forEach((input, index) => { ["red", "blue"].forEach((kind) => { if (input[kind] && !game.held[index][kind]) hit(game, index, kind); game.held[index][kind] = input[kind]; }); }); game.notes.forEach((note) => { if (!note.hit && game.frame - note.frame > 22) { note.hit = true; const player = game.players[note.player]; player.combo = 0; player.judge = "MISS"; } }); if (game.frame > game.notes.at(-1).frame + 150) { game.finished = true; game.winner = game.playerCount === 1 ? 0 : game.players[0].score === game.players[1].score ? -1 : game.players[0].score > game.players[1].score ? 0 : 1; } return game; }
export function drawRhythm(canvas, game) { const ctx=canvas.getContext("2d"), w=800,h=500;ctx.clearRect(0,0,w,h);if(rhythmBackground?.complete&&rhythmBackground.naturalWidth)ctx.drawImage(rhythmBackground,0,0,w,h);else{ctx.fillStyle="#f7eddb";ctx.fillRect(0,0,w,h);}ctx.fillStyle="rgba(31,27,24,.93)";ctx.fillRect(55,145,690,180);ctx.fillStyle="#f8e5bf";ctx.fillRect(112,222,5,82);ctx.fillStyle="#2c2521";ctx.font="700 20px sans-serif";ctx.fillText(game.song.title,45,48);ctx.font="13px sans-serif";ctx.fillText(`${game.song.composer}・${game.song.bpm} BPM・${game.song.difficulty}`,45,70);ctx.textAlign="right";ctx.font="700 17px sans-serif";ctx.fillStyle="#a4372c";ctx.fillText(`P1 ${game.players[0].score.toLocaleString()}　×${game.players[0].combo}`,755,48);if(game.playerCount===2){ctx.fillStyle="#2e6ba8";ctx.fillText(`P2 ${game.players[1].score.toLocaleString()}　×${game.players[1].combo}`,755,73);}ctx.textAlign="center";game.notes.filter(note=>!note.hit&&note.frame-game.frame<180&&note.frame-game.frame>-40).forEach(note=>{const x=116+(note.frame-game.frame)*3.25;ctx.fillStyle=note.kind==="red"?"#e54c37":"#3e8ad0";ctx.beginPath();ctx.arc(x,note.player===1?276:192,18,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff6df";ctx.lineWidth=4;ctx.stroke();});[[0,192,"#e54c37"],[1,276,"#3e8ad0"]].forEach(([player,y,color])=>{if(player===1&&game.playerCount===1)return;ctx.fillStyle=color;ctx.beginPath();ctx.arc(116,y,27,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff6df";ctx.lineWidth=5;ctx.stroke();ctx.fillStyle="#fff";ctx.font="bold 12px sans-serif";ctx.fillText(`P${player+1}`,116,y+4);});ctx.fillStyle="#fff7e1";ctx.font="700 18px sans-serif";ctx.fillText(game.players[0].judge,400,365);if(game.countdown>0){ctx.fillStyle="rgba(42,32,24,.65)";ctx.fillRect(305,145,190,170);ctx.fillStyle="#fff1ad";ctx.font="bold 74px monospace";ctx.fillText(Math.max(1,Math.ceil(game.countdown/60)),400,226);ctx.fillStyle="#fff";ctx.font="bold 15px sans-serif";ctx.fillText("準備演奏",400,267);}if(game.finished){ctx.fillStyle="rgba(42,32,24,.76)";ctx.fillRect(240,155,320,145);ctx.fillStyle="#fff1ad";ctx.font="bold 28px sans-serif";ctx.fillText(game.winner===-1?"平手！":`玩家 ${game.winner+1} 獲勝！`,400,218);ctx.fillStyle="#fff";ctx.font="15px sans-serif";ctx.fillText("選擇曲目再演奏一次",400,258);}}
